"""rename address

Revision ID: 36caef97ddbc
Revises: 60e90c2de5f9
Create Date: 2024-07-02 00:11:09.394283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36caef97ddbc'
down_revision = '60e90c2de5f9'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###