"""rename department

Revision ID: 60e90c2de5f9
Revises: 3dfbae963f53
Create Date: 2024-07-02 00:04:52.712124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e90c2de5f9'
down_revision = '3dfbae963f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###